# Generated by Django 4.1.7 on 2023-04-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Songs',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
